### ISSUE TITLE
HasGenericInterface does not Compile in Unity3D

### ISSUE THREAD

**Issue by ZuomingShi** [gering/Tiny-JSON#1]
In Unity3D Version 2018.1.0f2 Personal, I get the following error:

Assets/lib/Tiny-JSON/Tiny-JSON/Json.cs(81,54): error CS1644: Feature `nameof operator' cannot be used because it is not part of the C# 4.0 language specification

**Comment by ZuomingShi** [comment]
Since the operator was only used to name an exception, I used type.FullName instead of nameof(type).

**Comment by gering** [comment]
Thank you for the hint. The issue is resolved with version 1.1.1.
